import type { Metadata } from "next"
import { ThemeProvider } from "@/lib/providers/next-theme-provider"
import { Toaster } from "@/components/ui/toaster"
import { cn } from "@/lib/utils"
import SupabaseUserProvider from "@/lib/providers/user-provider"
import "./globals.css"
import AppStateProvider from "@/lib/providers/app-state-provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background text-foreground font-sans antialiased"
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="dark">
          <AppStateProvider>
            {children}
            <Toaster />
          </AppStateProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
